services:
  postgres:
    image: postgres:16-alpine
    container_name: p2p_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
    healthcheck:
      test: ["CMD-SHELL", "postgres -U ${POSTGRES_USER}"]
   
  redis:
    image: redis:7-alpine
    container_name: p2p_redis
    restart: unless-stopped
    env_file:
      - ../.env
    command: redis-server --bind 0.0.0.0
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    

volumes:
  postgres_data:
  redis_data:
